### ISSUE TITLE
SportSense.AI

### ISSUE THREAD

**Issue by Lifahlongwa** [BerkeAltiparmak/SportSense.AI#9]
Hi

I hope this message finds you well. I was curious after going through your project on athletes' performance, since I have not seen it yet. I am new to the coding world on python, and I am fascinated with sports but and I wanted to know if there was code that looked at a one specific player and tracked their games and measured their performance over x games. To analyze player specific task and roles in that game.
If you can help with just directing me to the right place I would appreciate it.

thank you

**Comment by Manit2210** [comment]
Hi

If you take a look at the BaLLR-1.ipynb notebook and check the def _get_player_game_indices method with the NBAFantasyDataset class you van check how we look back x number of games. This DataSet class is passed into the data loader which we use for training.
